version: '3.9'
services:
  work:
    build: .
    image: flask-app
    ports:
      - 5000:5000
    depends_on:
      - postgres
  postgres:
    image: db:v1
    env_file: .env
    expose:
      - 5432
